<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Some amazing website</title>
    <?php $this->assets->outputCss() ?>
</head>
<body>
<div class="container">

    <div class="jumbotron"><h1>Toets Maker</h1></div>

    {{navbar}}
    
    <div class="col-md-8"><h2 style="text-align: center;margin:  auto 0;">Nieuwe toets maken</h2>
        {{docmenu}}

        {{select}}

    </div>
    <div class="col-md-4">
        {{categorie}}
    </div>


</div>


<?php $this->assets->outputJs() ?>
</body>
<html>