<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Toetsen Maker - Toets Configureren</title>
    <?php $this->assets->outputCss() ?>
    <script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
</head>
    <body>
    <div class="container">

        <div class="jumbotron"><h1>Toets Maker</h1></div>


        {{navbar}}

        <div class="col-md-9">
            <h2 style="text-align: center;margin:  auto 0;">Toets Configureren</h2>
            {{docmenu}}

            {{formstart}}
                {{titel}}
                {{categorieen}}
                {{type}}
                {{starttext}}
                {{backgroundimage}}
                {{aantalvragen}}
                {{tijd}}
                {{submit}}
            {{formend}}
        </div>

        <div class="col-md-3">
            {{categorie}}
        </div>
    </div>
    {{footer}}

    <?php $this->assets->outputJs() ?>
    </body>
</html>