<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>

<a 
    href="#" 
    title="<?= $block->escapeHtml(__('Remove item')) ?>"
    class="cart-remove-link"
    data-post='<?= /* @noEscape */ $block->getDeletePostJson() ?>'
>
    <i class="cart-remove-icon fa fa-trash"></i>
</a>