<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >
    <title>Entree opleiding niveau 1 en 2s</title>
    <?php $this->assets->outputCss() ?>
</head>

<body>
{{background}}

<div id="box">


    <div id="title">
        <h1>{{title}}</h1>
    </div>

    <div id="content"">
    <p id="starttext">
        {{content}}
    </p>
</div>

<div id="start-wrapper" class="col-md-12">
    {{start}}
</div>
</div>


<?php $this->assets->outputJs() ?>

</body>
<html>