<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Toets maker</title>
    <?php $this->assets->outputCss(); ?>
</head>
<body>
<div class="container">

    {{error}}
    <div class="jumbotron"><h1>Toets Maker</h1></div>

    {{navbar}}
{{footer}}
<?php $this->assets->outputJs() ?>
</body>
<html>