<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>

<div class="block newsletter">
    <div class="inner">
        <h4 class="title">Become a MILLIONAIRE</h4>
        <p class="desc">Ontvang kortingen op de collectie die wij wekelijks aan jou presenteren, wordt jij onze nieuwe Big Spender?</p>
        <div class="content">
            <form class="form subscribe"
                novalidate
                action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                method="post"
                data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                id="newsletter-validate-detail">
                <div class="field newsletter">
                    <div class="control">
                        <label for="newsletter">
                            <span class="label">
                                <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                            </span>
                            <input name="email" type="email" id="newsletter"
                                placeholder="Voer je e-mail adres in..."
                                data-mage-init='{"mage/trim-input":{}}'
                                data-validate="{required:true, 'validate-email':true}"
                            />
                        </label>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary"
                            title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                            type="submit"
                            aria-label="Subscribe">
                        <span><i class="fa fa-angle-left"></i></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>